[programs.devnet]
twitterdapp = "8uQLNTb5sd8YieHMZ2TS4fj58g8rRC5E1cScmPA5CHj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/pickfordpatriot/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
